export const personal = {
  name: "Mohd Talib",
  title: "Senior Full Stack AI Engineer",
  tagline: "I build AI systems that ship. From RAG pipelines to production platforms, 0-to-1 in weeks.",
  email: "mohammad.talib319@gmail.com",
  phone: "+91 7408185999",
  linkedin: "https://linkedin.com/in/mohdtalib",
  github: "https://github.com/MohdTalib0",
  location: "India",
  available: true,
};

export const experience = [
  {
    role: "Senior Full Stack AI Engineer",
    badge: "Technical Lead",
    company: "TheAgentic AI",
    type: "Applied AI Research Company",
    location: "California, USA",
    remote: true,
    period: "Nov 2025 - Present",
    current: true,
    bullets: [
      "Sole technical lead across 3 production platforms, each shipped 0-to-1 (frontend + backend + infra) in 2-4 weeks with full client sign-off.",
      "Solunar (Health-Tech): Built async pipeline for vision + LLM-based tongue analysis, enabling automated metabolic insight generation. FastAPI + PostgreSQL + async SQLAlchemy.",
      "H2M (Reg-Tech): Replaced black-box RAG with deterministic SQL + LLM tool-use orchestration, making compliance workflows auditable. Next.js + FastAPI.",
      "Boxsy.io: Rewrote failing production platform end-to-end, eliminating critical failures and restoring stability within 2 weeks.",
      "KismetAI: Contributed to an AI ad-creation platform that generates and launches high-performing, on-brand ads in minutes across every major platform.",
    ],
    tags: ["FastAPI", "Next.js", "PostgreSQL", "OpenAI", "LangChain", "SQLAlchemy", "Anthropic"],
  },
  {
    role: "Senior Full Stack AI Engineer",
    badge: "Tech Lead",
    company: "Dumroo.ai",
    type: "AI-Powered EdTech",
    location: "New Jersey, USA",
    remote: true,
    period: "Mar 2025 - Nov 2025",
    current: false,
    bullets: [
      "Owned full technical org: hired engineers, conducted interviews, ran sprint planning, delivered KTs, coordinated with US school administrators.",
      "Built Dumroo 2.0 from scratch in 4 weeks, an AI-driven learning & assessment platform for K-12 schools.",
      "Designed RAG pipelines + agentic AI workflows, improving insight accuracy by 2x and reducing inference costs by 50%.",
      "Designed AI-powered Analytics and Personalized Learning engines, driving interest from 10+ school districts.",
      "Automated onboarding, achieving 10x reduction in school setup time. Promoted to Senior within 6 months.",
    ],
    tags: ["Next.js", "TypeScript", "Supabase", "RAG", "Agentic AI", "Vercel"],
  },
  {
    role: "Blockchain & Generative AI Engineer",
    company: "Lokachakra",
    type: "Decentralized Social Platform",
    location: "London, UK",
    remote: true,
    period: "Jan 2025 - Mar 2025",
    current: false,
    bullets: [
      "Built Web3 social collaboration platform on Sui/Aptos blockchain with zkAuth identity, OpenAI-powered content moderation, and real-time encrypted streaming chat.",
    ],
    tags: ["Sui", "Aptos", "zkAuth", "OpenAI", "Web3"],
  },
  {
    role: "Head of AI & Engineering",
    company: "CodeSpaze",
    type: "AI Education & Products",
    location: "Lucknow, India",
    remote: true,
    period: "Apr 2024 - Dec 2024",
    current: false,
    bullets: [
      "Led 20-member cross-functional team (engineers, designers, content, marketing). Drove 10x growth to 10K+ applicants in 2 months.",
      "Deployed production AI systems using LLMs, Hugging Face, and custom NLP pipelines. Mentored engineers in ML and full-stack development.",
    ],
    tags: ["LLMs", "Hugging Face", "NLP", "Team Leadership"],
  },
  {
    role: "Software Engineer & Data Analyst",
    company: "Techpile Technology",
    type: "Software Development",
    location: "Lucknow, India",
    remote: false,
    period: "Jul 2023 - Apr 2024",
    current: false,
    bullets: [
      'Built .NET APIs, data pipelines, and SQL dashboards for analytics. Automated data validation and preprocessing. Awarded "Best Performer: Software Developer" (2023).',
    ],
    tags: [".NET", "SQL", "Data Pipelines"],
  },
  {
    role: "Machine Learning Engineer",
    badge: "Data Engineering Lead",
    company: "Omdena",
    type: "Global AI for Social Good",
    location: "New York, USA",
    remote: true,
    period: "Mar 2023 - Jul 2023",
    current: false,
    bullets: [
      "Led 60+ AI engineers across 15+ countries as Data Engineering Lead. Built YOLOv8 + PyTorch pipelines on 100K+ annotated images for healthcare diagnostics (autism early detection) and infrastructure monitoring (pavement degradation).",
      "Coordinated across 15 time zones via GitHub and Slack, managing ML pipelines and research documentation.",
    ],
    tags: ["YOLOv8", "PyTorch", "TensorFlow", "Team Lead", "Computer Vision"],
  },
  {
    role: "Data Science & ML Engineering",
    company: "Multiple Organizations",
    type: "Innomatics, CodeClause, Sparks Foundation, Shiga Corp, Robust Results",
    location: "Remote",
    remote: true,
    period: "Jul 2022 - Jun 2023",
    current: false,
    bullets: [
      "Built CNN & YOLO models for plant disease detection, TensorFlow neural networks for forecasting systems, Flask web apps with embedded ML pipelines, and Java backend services.",
      "Led engineering team at Innomatics. Top 10, Data Science Hackathon (2023).",
    ],
    tags: ["CNN", "YOLO", "TensorFlow", "Flask", "Java"],
  },
];

export const projects = [
  {
    name: "Wrively",
    tagline: "Sound like yourself. Every time.",
    description: "Most AI writes for everyone. Wrively writes for you. Trained on how you think, what you believe, and how you sound at your best. Builds your voice once and writes from it forever. From topic to post in under 3 minutes.",
    tech: ["Next.js", "OpenAI API", "Supabase", "TypeScript", "Tailwind CSS"],
    live: "https://wrively.com",
    github: "https://github.com/MohdTalib0/FounderX",
    featured: true,
  },
  {
    name: "BlueDrum AI",
    tagline: "Your evidence, organized for your lawyer.",
    description: "Helps you collect chats, documents, and financial records, then organizes them into a structured case file your lawyer can actually use. Built for couples going through divorce, separation, or anyone needing legal evidence organized. No legal knowledge required.",
    tech: ["React", "FastAPI", "AI/ML", "PostgreSQL", "Tailwind CSS"],
    live: "https://bluedrumai.com",
    beta: "https://beta.bluedrumai.com",
    github: "https://github.com/MohdTalib0/BlueDrumAI",
    featured: true,
  },
  {
    name: "TalPred AI",
    tagline: "Production-grade equity alpha system.",
    description: "Automated daily cross-sectional equity predictions with paper trading and monitoring. End-to-end ML pipeline with model training, evaluation, and a real-time React dashboard.",
    tech: ["XGBoost", "PostgreSQL", "Redis", "MLflow", "React", "GitHub Actions"],
    github: "https://github.com/MohdTalib0/TalPred-AI",
    featured: true,
  },
  {
    name: "Dumroo 2.0",
    tagline: "AI-powered EdTech platform.",
    description: "Built from scratch in 4 weeks. AI-driven learning, assessment, and code-generation platform for US K-12 schools. RAG + Agentic AI workflows.",
    tech: ["Next.js", "TypeScript", "Supabase", "RAG", "Agentic AI"],
    featured: false,
  },
  {
    name: "Solunar Wellness",
    tagline: "AI health-tech backend.",
    description: "Async job pipeline for AI tongue-image analysis. Vision model to LLM reasoning to metabolic guidance. Multi-tenant APIs on FastAPI + PostgreSQL.",
    tech: ["FastAPI", "PostgreSQL", "OpenAI", "Computer Vision"],
    featured: false,
  },
  {
    name: "H2M Regulatory",
    tagline: "LLM-powered compliance platform.",
    description: "Regulatory intelligence with deterministic SQL + LLM tool-use orchestration. Ingests CFR/FDA data. Auditable, not a black-box.",
    tech: ["Next.js", "FastAPI", "LLM Agents", "PostgreSQL"],
    featured: false,
  },
  {
    name: "Fundalytics",
    tagline: "Discover Global Funding Opportunities with AI.",
    description: "AI platform that automatically discovers, matches, and applies to grants, VC funding, accelerators, and investment opportunities worldwide. Save 20+ hours/week, increase funding success rate by 300%.",
    tech: ["React", "AI/ML", "PostgreSQL", "Netlify"],
    live: "https://fundalytics.netlify.app",
    github: "https://github.com/MohdTalib0/Fundalytics",
    featured: false,
  },
  {
    name: "InvestLocal",
    tagline: "Connecting local entrepreneurs with smart investors.",
    description: "Platform bridging the gap between local entrepreneurs seeking funding and investors looking for smart, community-driven investment opportunities.",
    tech: ["React", "Node.js", "PostgreSQL", "Render"],
    live: "https://investlocal.onrender.com",
    github: "https://github.com/MohdTalib0/investlocal",
    featured: false,
  },
  {
    name: "CodeSpaze",
    tagline: "Global Tech Learning & Career Platform.",
    description: "Empowering the next generation of tech leaders with hands-on learning, real-world projects, and global opportunities. From internships to AI development.",
    tech: ["Next.js", "React", "AI/ML", "EdTech"],
    live: "https://www.codespaze.org",
    featured: false,
  },
  {
    name: "StackSage",
    tagline: "AI codebase intelligence.",
    description: "AI developer tool for codebase understanding and intelligent debugging using RAG + LLM orchestration.",
    tech: ["RAG", "LLM", "Python", "React"],
    github: "https://github.com/MohdTalib0/StackSage",
    featured: false,
  },
  {
    name: "AutoServeHub",
    tagline: "Automated AI deployment.",
    description: "Service management and deployment hub for AI-powered applications with automated CI/CD pipelines.",
    tech: ["FastAPI", "Docker", "CI/CD", "React"],
    github: "https://github.com/MohdTalib0/AutoServeHub",
    featured: false,
  },
];

export const skills = {
  "AI & LLM": ["RAG", "Agentic AI", "LLM Optimization", "Prompt Engineering", "Fine-tuning", "LangChain", "OpenAI API", "Anthropic API", "Hugging Face"],
  "Backend": ["FastAPI", "Node.js", "Express", "Django", "Flask", "SQLAlchemy", "Alembic", "REST APIs"],
  "Frontend & Mobile": ["Next.js", "React", "React Native", "TypeScript", "Tailwind CSS"],
  "ML & Data": ["PyTorch", "TensorFlow", "YOLOv8", "XGBoost", "Pandas", "Computer Vision", "MLflow", "Model Training & Deployment"],
  "Infrastructure": ["Docker", "AWS", "Azure", "GitHub Actions", "Vercel", "Netlify", "Render", "CI/CD"],
  "Databases & BaaS": ["PostgreSQL", "Supabase", "Firebase", "Neon", "MySQL", "Redis"],
};

export const stats = [
  { value: "5+", label: "Years Experience" },
  { value: "30+", label: "Products Shipped" },
  { value: "60+", label: "Engineers Led" },
  { value: "15+", label: "Countries Collaborated" },
];
